import * as admin from 'firebase-admin';

require('dotenv').config();

const firebaseApp = admin.initializeApp({
  credential: admin.credential.cert({
    projectId: process.env.FIREBASE_PROJECT_ID,
    privateKey: '-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQD3kMAzcIyIjcCL\nL2JHFk2Nn945nMC0ETv3tB3FoWTwMxjO8Xs+bDyzTaiTeR8eR/W3rSK6mUcNYIDB\nOk3ovm/lSROf3Ay0QGkS7ZvPEoVfdBVQxvZLoLBN64Jm1pHSxC5jiepb0HtT0IZm\nEfuixjUstPppzmgSXJTvT1ts4K/2kBRIOvY7O/bTltoCjb8+Pv7ByaaCcl1/0lIP\nkvqJbWDHPEvUyv9PCgMwopKKQT9CvTr1GnNCQkT7ymHvnLaOMOzmOIW5J8oB1joN\nbUdcHP6cugMi5efQm9xfHU22Cl43zhCkttbAzI3yHIwTZBFWSZk1HPWQtbBpM8rS\nPtCZyYvpAgMBAAECggEASasrZqNBTolQGJr7FchPP6upB1/cADl4rNdOXLcQQGIU\nKdC2KfcvgPPFDE1osywatJOy1/AwsoxbBCUDdhTlW0eJrXJf3WulWNqYGOCcC7GR\nfj4WoJ6qmCVS4qNLNXrnivtJYBUD/gb5V3pWdTOiMzGPqtifI4elUik9PYMHGclk\nSujSp1DIhtodkEv8MpeJuwd0whfTIjH8wVh5WkTPRJMCw2fIyPds5Lx7fmPJLze9\nWwPtYNomp5zlTFlZRuYiZBEkHgFmiv2RhXSOMzKfHx5XtLTRgRLkb/zkfqdpeaOa\n7u6oRr6zt5Gxypr7Le6DGj8T15qrt63BwpeZ0c9UOQKBgQD9SOZOHwWXcqFy40kY\nd/NeB4K0JRUHbvKwBOsuLNK31uaNBtPuhTtml1JcQJ2kn/eXbe5WdqdumHP6wB8O\nUinC6AAu72CilY+MyjRYyzUEOUP5uEZql3mSCeSgot8y93qCppVQ1zLtdTW0GGDk\nQPvzMfqiWlLV6fFY659BFuxgMwKBgQD6OCfEwE42iGIdL67DMyWU/BsbFxNjvmwT\n8GK3MQVVuP0K71OOD6pbb146gMgGBtAUilUJb6Ts4/yTv3vnMAmq3rIMgFpFyxph\nTBGidbJPsLTgmr07WqDkZ4duTuWlvME8NI9uecyG3Fd7Ax1amF2tCczXfviPpKbY\ntLJ1NnNXcwKBgQCb73G6zuaGYxB6xuuNoOu4DC+v8NSNiwTm0WBpQTdJ74hpcrav\ntl7nvmn6Wd20KLgqBoghu1NBh6J/0iBMlNEZKfRS8RUxg5qpNyQbNqAhRZBQAd94\naGF0Q5r6OsvneO132k87QgIcp3i0s/2TCV8UTsTbh3hQMoNgF1AoppBIeQKBgHAV\nqZLUBfUdoL2sN1/PUH1tdQLskk3y5d0EqGOhPN+Kbydvz4DqeYhd2drhBzjT4m/h\nC3ifn0RSWDki5HDKLvpwqVc6Q7XR5i5BcgDRMh/KayvVhQDKdxn5WkxKYUqdw/2h\nGcMGIl0i5LkAyyxi5kt2AWFiyhsmSWr3fp1M19wLAoGABcjxA4UzSoDjizon52bV\nmjvjg23hWQ5n6EQK1oXRsJ/OnbVMaWDqNXmPcMyanspeEHQajd0grt67OUTkQG8I\npmc+1TprGAnMCrhdx8kmbh07xRbBn6AV387avCQehkzT4cZvjIOOAAyXPd6KUmN2\nZ/V27ExDwI7QKelhAdqQHuM=\n-----END PRIVATE KEY-----\n',
    clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
    type: process.env.FIREBASE_TYPE,
    privateKeyID: process.env.FIREBASE_PRIVATE_KEY_ID,
    clientID: process.env.FIREBASE_CLIENT_ID,
    authUri: process.env.FIREBASE_AUTH_URI,
    tokenUri: process.env.FIREBASE_TOKEN_URI,
    authProviderX509CertUrl: process.env.FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
    clientX509CertUrl: process.env.FIREBASE_CLIENT_X509_CERT_URL,
    universeDomain: process.env.FIREBASE_UNIVERSE_DOMAIN,
  }),
});

export default firebaseApp;
